begin;

/* Especifica as chaves estrangeiras */
ALTER TABLE EMPREGADO    ADD FOREIGN KEY (NSUPER) REFERENCES EMPREGADO(NUMAT);
ALTER TABLE EMPREGADO    ADD FOREIGN KEY (NDEPTO) REFERENCES DEPARTAMENTO(NUMDEP);
ALTER TABLE DEPARTAMENTO ADD FOREIGN KEY (NCHEFE) REFERENCES EMPREGADO(NUMAT);
ALTER TABLE PROJETO      ADD FOREIGN KEY (NUMDEP) REFERENCES DEPARTAMENTO(NUMDEP);
ALTER TABLE DEPENDENTE   ADD FOREIGN KEY (NUMEMP) REFERENCES EMPREGADO(NUMAT);
ALTER TABLE LOCALDEPTO   ADD FOREIGN KEY (NUMDEP) REFERENCES DEPARTAMENTO(NUMDEP);
ALTER TABLE TRABALHAEM   ADD FOREIGN KEY (NUMEMP) REFERENCES EMPREGADO(NUMAT);
ALTER TABLE TRABALHAEM   ADD FOREIGN KEY (NPROJ)  REFERENCES PROJETO(NUMPROJ);

/* fim */
COMMIT;
